# route for all users
# 
homepage:
    path: /
    controller: App\Controller\Front\BlogController::index

show_article:
    path: /show/{id}
    controller: App\Controller\Front\BlogController::show

comment:
    path: /comment/article/{id}
    controller: App\Controller\Front\BlogController::comment

show_reply:
    path: /comment/{id}/show
    controller: App\Controller\Front\BlogController::replyComment

comment_reply:
    path: /comment/{id}/reply
    controller: App\Controller\Front\BlogController::replyComment
display_reply:
    path: /comment/{id}/display-reply
    controller: App\Controller\Front\BlogController::displayReply