# route for all users
# 
homepage:
    path: /
    controller: App\Controller\BlogController::index

show_article:
    path: /show/{id}
    controller: App\Controller\BlogController::show

comment:
    path: /comment/article/{id}
    controller: App\Controller\BlogController::comment

show_reply:
    path: /comment/{id}/show
    controller: App\Controller\BlogController::replyComment

comment_reply:
    path: /comment/{id}/reply
    controller: App\Controller\BlogController::replyComment
display_reply:
    path: /comment/{id}/display-reply
    controller: App\Controller\BlogController::displayReply
# route for admin only
# 
# admin:
#     path: /admin
#     controller: App\Controller\BlogController::admin

# add_article:
#     path: /admin/add
#     controller: App\Controller\BlogController::add

# edit_article:
#     path: /admin/edit/{id}
#     controller: App\Controller\BlogController::edit
#     requirements: 
#         id: '\d+'

# remove_article:
#     path: /admin/remove/{id}
#     controller: App\Controller\BlogController::remove 
#     requirements: 
#         id: '\d+'
         